namespace Schema.NET
{
    using System;
    using System.Text.Json;
    using System.Text.Json.Serialization;

    /// <summary>
    /// A Report generated by governmental or non-governmental organization.
    /// </summary>
    public partial interface IReport : IArticle
    {
        /// <summary>
        /// The number or other unique designator assigned to a Report by the publishing organization.
        /// </summary>
        OneOrMany<string> ReportNumber { get; set; }
    }

    /// <summary>
    /// A Report generated by governmental or non-governmental organization.
    /// </summary>
    public partial class Report : Article, IReport
    {
        /// <summary>
        /// Gets the name of the type as specified by schema.org.
        /// </summary>
        [JsonPropertyName("@type")]
        public override string Type => "Report";

        /// <summary>
        /// The number or other unique designator assigned to a Report by the publishing organization.
        /// </summary>
        [JsonPropertyName("reportNumber")]
        [JsonConverter(typeof(ValuesJsonConverter))]
        public OneOrMany<string> ReportNumber { get; set; }
    }
}
